config/routes.rb
CumploApp::Application.routes.draw do
  resources :prospectos

  get "cliente/index"

  get "proxy/index"
  get "channels/index"
  get "cumplo/index"

  
  root :to => 'cumplo#index'
  match '/cliente(/:channel_id)' => "cliente#suscribirse"

   match ':controller(/:action(/:id))(.:format)'
end

app/models/prospecto.rb
class Prospecto < ActiveRecord::Base
  attr_accessible :edad, :email, :nombre
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
 
  
end

app/controllers/cliente_controller.rb
class ClienteController < MobileController
  
  def index
    
    
  end
  
  
  def suscribirse
    
    @app_url = App_url
    @socket_url = Socket_url
    @channel_id = params[:channel_id]
    
    @prospecto = Prospecto.new
    
  end
  
  
end

app/controllers/cumplo_controller.rb
class CumploController < ApplicationController
  protect_from_forgery
  def index
    
    time = Time.new
    @socketid = time.hour+time.min+time.sec+time.usec
    @app_url = App_url
    @socket_url = Socket_url
    
    @prospecto = Prospecto.new
        
  end
  
 
  
end

app/controllers/mobile_controller.rb
class MobileController < ActionController::Base
  protect_from_forgery
  
 
  
end

app/controllers/prospectos_controller.rb
class ProspectosController < ApplicationController
  # GET /prospectos
  # GET /prospectos.json
  def index
    @prospectos = Prospecto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @prospectos }
    end
  end

  # GET /prospectos/1
  # GET /prospectos/1.json
  def show
    @prospecto = Prospecto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @prospecto }
    end
  end

  # GET /prospectos/new
  # GET /prospectos/new.json
  def new
    @prospecto = Prospecto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @prospecto }
    end
  end

  # GET /prospectos/1/edit
  def edit
    @prospecto = Prospecto.find(params[:id])
  end

  # POST /prospectos
  # POST /prospectos.json
  def create
    @prospecto = Prospecto.new(params[:prospecto])

    respond_to do |format|
      if @prospecto.save
        format.html { redirect_to @prospecto, notice: 'Prospecto creado correctamente.' }
        format.json { render json: @prospecto, status: :created, location: @prospecto }
      else
        format.html { render action: "new" }
        format.json { render json: @prospecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /prospectos/1
  # PUT /prospectos/1.json
  def update
    @prospecto = Prospecto.find(params[:id])

    respond_to do |format|
      if @prospecto.update_attributes(params[:prospecto])
        format.html { redirect_to @prospecto, notice: 'Prospecto actualizado correctamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @prospecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prospectos/1
  # DELETE /prospectos/1.json
  def destroy
    @prospecto = Prospecto.find(params[:id])
    @prospecto.destroy

    respond_to do |format|
      format.html { redirect_to prospectos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/cliente_helper.rb
module ClienteHelper
end

app/helpers/cumplo_helper.rb
module CumploHelper
end

app/helpers/prospectos_helper.rb
module ProspectosHelper
end

app/helpers/proxy_helper.rb
module ProxyHelper
end

app/views/cliente/suscribirse.html.erb
<script type="text/javascript">


  
jQuery(document).ready(
function() {
       
   var CumploSocket = new Socketjs('<%=@socket_url%>?canal_id=<%=@channel_id%>');
      
      
   jQuery("#prestamista_btn").click(function() {
      
      console.log(<%=@channel_id%>);
     CumploSocket.send("accion","prestamista","movil",<%=@channel_id%>);
     
   });
   
   jQuery("#consumidor_btn").click(function() {
     
      console.log(<%=@channel_id%>); 
      CumploSocket.send("accion","consumidor","movil",<%=@channel_id%>);
     
     
   });
   
   
   jQuery("#contacto_btn").click(function() {
     CumploSocket.send("accion","contacto","movil",<%=@channel_id%>);
   });
   
   
    jQuery("#gracias_container").css({"display":"none"});
    
    
   jQuery("#continuar_btn").click(function() {
     CumploSocket.send("nombre",jQuery("#prospecto_nombre").val(),"movil",<%=@channel_id%>);
     jQuery("#form_container").hide();
     jQuery("#gracias_container").show();
   });
   
   function procesar_mensaje(data) {
      
      switch(data.mensaje) {
        
        /*case "formulario":
         
            jQuery("#contacto_btn").show("slow");
        break;*/
        
       
      }
      
  }
  
   
   
    CumploSocket.bind( 'open', function (data) {
      console.log("se ha abierto un canal "+data);
    });
    
    CumploSocket.bind( 'mensaje', function (data) {
       console.log("se ha enviado un mensaje "+data);
       procesar_mensaje(data)
    });
    
    CumploSocket.bind( 'close', function (data) {
       console.log("se ha cerrado un canal "+data);
    });
    
    CumploSocket.bind( 'silencio', function (data) {
       console.log(data);
    });
    
}
);

</script>

<div data-role="page">

	<div data-role="header">
		<h1>Cumplo.cl</h1>
	</div><!-- /header -->

	<div data-role="content">	
		
                <h1>Bienvenido a Cumplo.cl</h1>
                
                <p>Se ha suscrito al canal <%=@channel_id%></p>
                
                <p>Conozca los beneficios de Cumplo como prestamista o consumidor</p>
                <p>Seleccione ver los beneficios para: </p>
                
                <a id="prestamista_btn" href="#" data-role="button" data-icon="star">Quiero Invertir</a>
                <a id="consumidor_btn" href="#" data-role="button" data-icon="star">Quiero Pedir Prestado</a>
                
                <a id="contacto_btn"  href="#contacto" data-role="button" data-icon="star">Contacto</a>
        
        </div><!-- /content -->
</div><!-- /page -->

<div id="contacto" data-role="page">

	<div data-role="header">
		<h1>Cumplo.cl</h1>
	</div><!-- /header -->

	<div data-role="content">	
		
            <div id="form_container">
              
             <h1>Más Infomración!</h1>
              <p> Ingresa tu nombre </p>
              
              
             
                <form accept-charset="UTF-8" action="" class="new_prospecto" id="new_prospecto" method="post">

                  <div class="field">
                    <label for="prospecto_nombre">Nombre</label><br />
                    <input id="prospecto_nombre" name="prospecto[nombre]" size="30" type="text" />
                  </div>

                  <div class="actions">
                    <input id="continuar_btn" name="continuar_btn" type="button" value="Continuar" />
                  </div>
             
                </form>
                
              </div>
          
              <div id="gracias_container">
                 <h1>Gracias <span id="nombre_contaner"></span></h1>
                <p> Por favor completa el formulario en tu comptador </p>

              </div>
          
          
          
          
              </div>
              
              
        
        </div><!-- /content -->
</div><!-- /page -->

app/views/cumplo/index.html.erb
<script type="text/javascript">
  
  
    
  jQuery(document).ready(function() {
    
    //Tenemos que abrir el canal del socket ahora
   
    var CumploSocket = new Socketjs('<%=@socket_url%>?canal_id=<%=@socketid%>');
    
    CumploSocket.bind( 'open', function (data) {
      console.log("se ha abierto un canal "+data);
    });
    
    CumploSocket.bind( 'nombre', function (data) {
      
      jQuery("#prospecto_nombre").val(data.mensaje);
      jQuery(".page").slideUp();
      jQuery(".contacto").show("slow");
      
    });
    
    CumploSocket.bind( 'accion', function (data) {
       console.log("se ha enviado un mensaje "+data);
       procesar_mensaje(data)
    });
    
   
    
    CumploSocket.bind( 'close', function (data) {
       console.log("se ha cerrado un canal "+data);
    });
    
    CumploSocket.bind( 'silencio', function (data) {
       console.log(data);
    });
    
     
    CumploSocket.bind( 'page', function (data) {
      
       console.log(data);
    });
    
    
    //Generamos el codigo qr que envia el id del canal a la aplicación mobile para que el usuario pueda unirse.
    jQuery('#qr').qrcode("<%=@app_url%>/cliente/<%=@socketid%>");
    
    
    jQuery(".page").css({'height': (getDocHeight()-100) + 'px'});
    
    jQuery(window).resize(function() {
       jQuery(".page").css({'height': (getDocHeight()-100) + 'px'});
    });
    
    
    
    function procesar_mensaje(data) {
      
      switch(data.mensaje) {
        
        case "consumidor":
           jQuery(".page").slideUp();
           jQuery(".prestamista").show("slow");
          
           //CumploSocket.send("accion","formulario","pc",<%=@socketid%>);
        break;
        
        case "prestamista":
          jQuery(".page").slideUp();
          jQuery(".consumidor").show("slow");
         
          //CumploSocket.send("accion","formulario","pc",<%=@socketid%>);
        break;
        
        
        case "contacto":
         
         
        
        break;
        
        
        
          
      }
      
  }
    
    
    
   

           jQuery.extend(jQuery.validator.messages, {
                required: "Campo obligatorio",
                remote: "Pro favor corrige este campo",
                email: "Ingrese una direccion de email valida",
                url: "Ingrese una url valida",
                date: "Ingrese una fecha valida",
                dateISO: "Ingrese una fecha valida (ISO)",
                number: "Ingrese un numero",
                digits: "Ingrese solo digitos",
                creditcard: "Ingrese un numero de tarjeta valida",
                equalTo: "Ingrese el mismo valor",
                accept: "Ingrese una extension valida",
                maxlength: jQuery.validator.format("No es posible ingresar mas de {0} catacteres"),
                minlength: jQuery.validator.format("Ingrese al menos {0} caracteres"),
                rangelength: jQuery.validator.format("Ingrese un valor con un minimo {0} y maximo {1} caracteres"),
                range: jQuery.validator.format("Ingrese un valor entre {0} y {1}"),
                max: jQuery.validator.format("Ingrese un valor menor o igual a {0}"),
                min: jQuery.validator.format("Ingrese un valor mayor o igual a {0}")
            });       





     jQuery('#new_prospecto').validate({

   	 highlight: function(element, errorClass) {
           $(element).removeClass("valid").removeClass("warning").addClass("warning");
         },
         unhighlight: function(element, errorClass) {
          $(element).addClass("valid").removeClass("warning");
         },

                errorClass: "warning",
                debug:false,
                onkeyup: true,
                onblur: true,
                ignore:':hidden'
                
        });  
        
        
 jQuery("#gracias_container").css({"display":"none"});


      $('#new_prospecto').submit(function(e) {
        e.preventDefault();
        
        if($("#new_prospecto").valid()) {
        
          var dataString = { "prospecto" : {
            
            "nombre" : jQuery("#prospecto_nombre").val(),
            "email" : jQuery("#prospecto_email").val(),
            "edad" : jQuery("#prospecto_edad").val()
          
          } }
          
          console.log(dataString);
          
          jQuery.ajax({  
            type: "POST",  
            url: "/prospectos.json",  
            data: dataString,  
            success: function(data) {  
              
              console.log(data);
              
              jQuery("#name_txt").html(data.nombre)
              jQuery("#fecha_txt").html(data.created_at)
              
              jQuery("#form_container").hide();
              jQuery("#gracias_container").show("slow");
              
              
            },
            error: function(e) {
              console.log("error "+e);
            }
          });  
        }

        
        return false;
      });





    
  });
  
  
  
  
  
  
  function getDocHeight() {
    var D = document;
    return Math.max(
        Math.max(D.body.scrollHeight, D.documentElement.scrollHeight),
        Math.max(D.body.offsetHeight, D.documentElement.offsetHeight),
        Math.max(D.body.clientHeight, D.documentElement.clientHeight)
    );
  }
  
  
</script>



<div class="page" id="page-1">
  
  

  <div class="content_box">
     <div id="qr">  
     </div>
  </div>

</div>

<div class="page consumidor" id="page-2">
  <div class="content_box">
    <h1> Consumidor </h2>
    <p> lkdlfkjgldkjfgd </p>
  </div>
  
</div>

<div class="page prestamista" id="page-3">
  <div class="content_box">
    
    <h1>En Cumplo existen nuevas alternativas de inversión para ti</h1>

    <p>Hola, si buscas nuevas alternativas de inversión, conoce lo que Cumplo ofrece para inversionistas como tú.
      En Cumplo puedes prestar tus fondos a personas reales, con necesidades reales y lo mejor de todo es que tú decides a quién le prestas y la tasa de interés mínima a la cual estás dispuesto a prestar tu dinero.
      Rápido, simple y seguro. Únete hoy a Cumplo y sé parte de la primera comunidad de créditos persona-a-persona en Chile.
    </p>
    
  </div>
  
</div>


<div class="page contacto" id="page-4">
  
  <div class="content_box">
    
    <h1>Contacto</h1>

    <div id="form_container">
    
       <%= form_for(@prospecto) do |f| %>
                <% if @prospecto.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@prospecto.errors.count, "error") %> prohibited this prospecto from being saved:</h2>

                    <ul>
                    <% @prospecto.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                    <% end %>
                    </ul>
                  </div>
                <% end %>

                <div class="field">
                  <%= f.label :nombre %><br />
                  <%= f.text_field :nombre, :class => 'required' %>
                </div>
                <div class="field">
                  <%= f.label :email %><br />
                  <%= f.text_field :email, :class => 'required email' %>
                </div>
                <div class="field">
                  <%= f.label :edad %><br />
                  <%= f.text_field :edad, :class => 'required'%>
                </div>
                <div class="actions">
                  <%= f.submit %>
                </div>
              <% end %>
    
    </div>
    
     <div id="gracias_container">
       
       Grcias <span id="name_txt"></span>, hemos guardado tu información con fecha <span id="fecha_txt"></span>,
       Pronto te contactaremos.
    
     </div>
       
       
  </div>
  
</div>




<div class="debug">
  <%=@socketid%>
  <%=@app_url%>
  <%=@socket_url%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CumploApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="logo">
    <%= image_tag "logo.png" %>
</div>
  
<%= yield %>

</body>
</html>

app/views/layouts/mobile.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CumploApp Mobile</title>
  
  <%= javascript_include_tag "http://code.jquery.com/jquery-1.6.4.min.js" %>
  <%= javascript_include_tag "socketjs" %>
  <%= javascript_include_tag "http://code.jquery.com/mobile/1.1.0/jquery.mobile-1.1.0.min.js" %>
  <%= stylesheet_link_tag "http://code.jquery.com/mobile/1.1.0/jquery.mobile-1.1.0.min.css" %>

  
</head>
<body>

<%= yield %>

</body>
</html>

app/views/prospectos/_form.html.erb
<%= form_for(@prospecto) do |f| %>
  <% if @prospecto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prospecto.errors.count, "error") %> prohibited this prospecto from being saved:</h2>

      <ul>
      <% @prospecto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :edad %><br />
    <%= f.text_field :edad %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/prospectos/edit.html.erb
<div class="page" id="page-1">
  
 
<div class="content_box">
 
<h1>Editing prospecto</h1>
<%= render 'form' %>
<%= link_to 'Listado', @prospecto %> |
<%= link_to 'Volver', prospectos_path %>
</div>
  
</div>

app/views/prospectos/index.html.erb
<div class="page" id="page-1">
  
 
<div class="content_box">
  


<h1>Lista de prospectos</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Email</th>
    <th>Edad</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @prospectos.each do |prospecto| %>
  <tr>
    <td><%= prospecto.nombre %></td>
    <td><%= prospecto.email %></td>
    <td><%= prospecto.edad %></td>
    <td><%= link_to 'Mostrar', prospecto %></td>
    <td><%= link_to 'Editar', edit_prospecto_path(prospecto) %></td>
    <td><%= link_to 'Borrar', prospecto, confirm: 'Esta seguro?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nuevo Prospecto', new_prospecto_path %>


  
</div>
  
  
</div>

app/views/prospectos/new.html.erb
<div class="page" id="page-1">
  
 
<div class="content_box">
  <h1>Nuevo prospecto</h1>
  <%= render 'form' %>
  <%= link_to 'Volver', prospectos_path %>
</div>
  
  
</div>

app/views/prospectos/show.html.erb
<div class="page" id="page-1">
  
 
<div class="content_box">

<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @prospecto.nombre %>
</p>

<p>
  <b>Email:</b>
  <%= @prospecto.email %>
</p>

<p>
  <b>Edad:</b>
  <%= @prospecto.edad %>
</p>


<%= link_to 'Editar', edit_prospecto_path(@prospecto) %> |
<%= link_to 'Volver', prospectos_path %>

</div>
  
</div>